config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
        resources :applicants, only: [ :index, :show ] do
        resources :addresses, only: [ :create, :update, :destroy ]
        resources :contacts, only: [ :create, :update, :destroy ]
      end

      post 'calculate_inss', to: 'inss#calcule_inss'
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'

  resources :sessions, only: [ :create ]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  post 'authenticate', to: 'authentication#authenticate'

  resources :applicants, only: [ :index, :show, :new, :create ]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Inss Final"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    = javascript_importmap_tags
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    .container-fluid
      .row
        #sidebar.bg-dark.d-flex.flex-column.justify-content-between
          .d-flex.flex-column.align-items-start.pt-3
            %button#sidebar-toggle.btn.btn-light
              %i.fas.fa-bars
            .sidebar-header.ms-3
              Menu
            %ul.nav.flex-column.mt-4
              %li.nav-item
                = link_to root_path, data: { turbo_frame: "main_frame" }, class: "nav-link text-light d-flex align-items-center" do
                  %i.fas.fa-home
                  %span.ms-2 Home
              %li.nav-item
                = link_to applicants_path, data: { turbo_frame: "main_frame" }, class: "nav-link text-light d-flex align-items-center" do
                  %i.fas.fa-users
                  %span.ms-2 Proponentes
          .mt-auto.mb-4
            %li.nav-item
              %button{ type: "submit", class: "btn btn-link text-danger", form: "logout-form" }
                %i.fas.fa-sign-out-alt
                %span.ms-2 Sair
              = form_with url: logout_path, method: :delete, id: "logout-form", class: "d-none" do
                %input{ type: "hidden", name: "dummy", value: "dummy" }

        #main-content.col-md-10.offset-md-2.p-5
          %turbo-frame#main_frame
            = yield

app/views/layouts/login.html.haml
!!! 5
%html
  %head
    %meta{ charset: "UTF-8" }
    %title= content_for(:title) || "Login - Inss Challenge"
    %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: "/icon.png", rel: "icon", type: "image/png" }
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "bootstrap.min", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = turbo_include_tags
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  %body
    - flash.each do |key, message|
      .alert.alert-dismissible{ class: "alert-#{key}" }
        %button.close{ "aria-label" => "Close", "data-bs-dismiss" => "alert" }
          %span{ "aria-hidden" => "true" } &times;
        = message

    .container.d-flex.justify-content-center.align-items-center.min-vh-100
      .card.shadow-sm.p-4(style="max-width: 400px;")
        %h2.text-center Seja Bem-Vindo
        = yield